services:
  web:
    build: apps/web
    ports:
      - "5555:3000"
    depends_on:
      - extractor
    environment:
      HTTP_ENDPOINT: http://localhost:4000/graphql

  extractor:
    build: apps/extractor
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      HOST: 0.0.0.0
      MONGODB_URI: mongodb://mongo:27017
      GITHUB_TOKEN: ${GITHUB_TOKEN}

  mongo:
    image: "mongo"
